### PR TITLE
Validate JWT against a JWKSet instead of JWK

### PR DESCRIPTION
**Pull request by sopvop**
This is useful if you rotate keys with short expiration time.

### CODE REVIEW

**Comment by domenkozar** [comment]
`key` should be removed, otherwise someone might mistakingly set it and expect verification to work.

**Comment by sopvop** [comment]
`key` is used to sign session cookie JWTs and must be a private key. Validation can be done with public JWKs.

In my case I don't use session cookies. I have other service give out JWT bearer tokens and public keys which can be used to validate these other tokens.

Maybe it would be better to rename both `key` and `keySet` fields to more descriptive names?
Would something like `signingKey` and `verificationKeys` be better?

**Comment by jkarni** [comment]
:+1: to renaming as suggested

**Comment by sopvop** [comment]
Rebased against master and renamed fields to match their usage.
```haskell
data JWTSettings = JWTSettings
  {
  -- | Key used to sign JWT.
    signingKey      :: Jose.JWK
  -- | Algorithm used to sign JWT.
  , jwtAlg          :: Maybe Jose.Alg
  -- | Keys used to validate JWT.
  , validationKeys  :: Jose.JWKSet
  -- | An @aud@ predicate. The @aud@ is a string or URI that identifies the
  -- intended recipient of the JWT.
  , audienceMatches :: Jose.StringOrURI -> IsMatch
  } deriving (Generic)

```

**Pull request merged**
