### PR TITLE
client: Support generic Bearer token auth

### LINKED ISSUE #162: Generalise authentication client to Bearer
The library provides multiple server-side authentication implementations and matching client-side implementations. It makes sense that these implementations need to be very specific on the server, but not so much on the client.

What I mean is that the code that implements `JWT` auth on the client actually has nothing at all specific to JWT and would work equally well for any `Bearer` authentication based system. I haven’t tried yet, but looking at the code, it looks like I can simply declare an API type using `Auth '[JWT]` and will be able to use the resulting client with any server that wants a Bearer token. However it will look weird.

So what I’m thinking is that it might be a good idea to define `Bearer` authentication solely in `servant-auth-client` and use the current `JWT` code for it and then also provide actual `JWT` instances going through the same code path.

Of course, there will only by `HasClient` for the resulting API type with `Bearer` and no `HasServer`.

### PR DESCRIPTION
**Pull request by kirelagin**
Resolves #162.

### CODE REVIEW

**Comment by kirelagin** [comment]
It doesn’t affect `JWT` in any way. So, if you have `JWT` in your server, you’ll get `JWT` in the client, and it will work just as before.

It only _adds_ this unspecified `Bearer` type. The use case is generating clients for “external” servers that are not implemented in `servant`, and do not necessarily advertise what exactly their token is – they just tell you to use `Bearer` and paste this opaque string, which means something to them.

**Comment by kirelagin** [comment]
Oh, and just to clarify, even before this PR one could generate such a client specifying `JWT` as the auth type and then providing the opaque token. It is just a little weird, if that’s an opaque bearer token rather than a real JWT.

**Comment by fisx** [comment]
@alpmestan could you make @arianvp and @fisx owner of haskell-servant so I can merge this?

**Comment by fisx** [comment]
thanks!  :)

**Pull request merged**
