### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by freckletonj**
The black and white rendering of your documentation is tough for me to parse, but it seems it was close to what github expected.

Perhaps you'll like it when github renders it with color?

### CODE REVIEW

**Comment by freckletonj** [comment]
This is what it'd look like: https://github.com/freckletonj/servant-auth

**Comment by jkarni** [comment]
Perfect! Could you copy that to `servant-auth-server/executables/README.lhs`? There's a check in CI to make sure the readme matches that so that we try building the README (symlinks don't work nicely with git)

**Comment by freckletonj** [comment]
phew, just cracked the code. Are you using pandoc?

if so, you're probably doing something like:

``` sh
pandoc -f markdown+lhs -t markdown+lhs -o README.md servant-auth-server/executables/README.lhs 
```
That markdown isn't the appropriate github flavor, but you _do_ already have the appropriate syntax-highlighting-code-name in your `.lhs`.

You need to use a `-t` flag like this, specifying github-flavored-markdown:

``` sh
pandoc -f markdown+lhs -t markdown_github -o blorp.md servant-auth-server/executables/README.lhs 
#or if you're on a v2.0 branch of pandoc:
pandoc -f markdown+lhs -t gfm -o blorp.md servant-auth-server/executables/README.lhs 
```

**Comment by domenkozar** [comment]
#100

**Pull request closed without merging**
