### PR TITLE
Allow servant-0.15

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by domenkozar** [comment]
Anything else to do before I merge and release?

**Comment by phadej** [comment]
Something is blocking `servant-0.15`

```
 - servant-server-0.14.1 (lib:servant-server) (requires download & build)
 - servant-client-0.14 (lib) (requires download & build)
```

**Comment by domenkozar** [comment]
@phadej could you provide more context?

**Comment by phadej** [comment]
Ah, needs `servant-swagger` release.

**Comment by domenkozar** [comment]
If so, shouldn't we just set `servant >= 0.13` in all cabal files?

**Comment by phadej** [comment]
@domenkozar, yes, that would be good thing to do.

About releases: I'd prefer revisions, even we restrict lower-bound (as it cannot really break anyone).

**Comment by domenkozar** [comment]
If we don't enforce `http-api-data` version, we'll have to CPP https://github.com/haskell-servant/servant-auth/commit/2fee41847d9801ac50e6eb7eb64806ed2cf5b34a

**Comment by phadej** [comment]
> 2fee418

good point

**Comment by domenkozar** [comment]
I've made the most minimal changes to allow servant-0.15 with revisions on hackage.

**Comment by domenkozar** [comment]
Maybe just enforcing `http-api-data > 0.3.8` is easier?

**Pull request merged**
