### PR TITLE
Allow base-4.13, time-1.9, lens-4.18, ...

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Ok. Old jobs timeout. And GHC-8.8 is blocked on 
```
[__6] fail (backjumping, conflict set: asn1-encoding, base, x509)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: base, x509, asn1-encoding, servant-auth-client, jose, servant-auth-client:test, servant-auth
```

at least `asn1-encoding` needs a proper release (not only bound relaxation), so let's wait.

**Comment by domenkozar** [comment]
@phadej RSA 2.4.1 was released, but it's still picking up RSA 2.3.1

**Comment by domenkozar** [comment]
Blocked on https://github.com/frasertweedale/hs-jose/pull/87

**Comment by phadej** [comment]
`servant-auth-client` tests are unacceptably slow

```
% timeout 300 cabal run -w ghc-8.6.5 --enable-tests --enable-benchmarks servant-auth-client:spec
Up to date

Servant.Auth.Client
  The JWT combinator
    HasClient
61/100

% echo $?
124
```

5 minutes weren't enough to run the first test on my relatively fast machine.

Maybe something changed in dependencies?

```
PkgId (PkgName "servant-auth-client") (Ver [0,4,0,0])
CompNameLib
  base-4.12.0.0
  bytestring-0.10.8.2
  containers-0.6.0.1
  servant-0.16.2
  servant-auth-0.3.2.0
  servant-client-core-0.16

PkgId (PkgName "servant-auth-client") (Ver [0,4,0,0])
CompNameTest "spec"
  QuickCheck-2.13.2
  aeson-1.4.6.0
  base-4.12.0.0
  bytestring-0.10.8.2
  hspec-2.7.1
  http-client-0.6.4
  http-types-0.12.3
  jose-0.8.2.0
  servant-0.16.2
  servant-auth-0.3.2.0
  servant-auth-client-0.4.0.0
  servant-auth-server-0.4.4.0
  servant-client-0.16.0.1
  servant-server-0.16.2
  time-1.8.0.2
  transformers-0.5.6.2
  wai-3.2.2.1
  warp-3.3.4

PkgId (PkgName "servant-auth-server") (Ver [0,4,4,0])
CompNameLib
  aeson-1.4.6.0
  base-4.12.0.0
  base64-bytestring-1.0.0.2
  blaze-builder-0.4.1.0
  bytestring-0.10.8.2
  case-insensitive-1.2.1.0
  cookie-0.4.5
  data-default-class-0.1.2.0
  entropy-0.4.1.5
  http-types-0.12.3
  jose-0.8.2.0
  lens-4.18.1
  memory-0.15.0
  monad-time-0.3.1.0
  mtl-2.2.2
  servant-0.16.2
  servant-auth-0.3.2.0
  servant-server-0.16.2
  tagged-0.8.6
  text-1.2.3.1
  time-1.8.0.2
  unordered-containers-0.2.10.0
  wai-3.2.2.1
```

**Comment by domenkozar** [comment]
Must be as running with LTS-14.4 they pass in less than a second.

**Comment by phadej** [comment]
In comparison, `master` branch 

```
% time cabal build -w ghc-8.6.5 --enable-tests --enable-benchmarks servant-auth-client:spec                       
Up to date
cabal build -w ghc-8.6.5 --enable-tests --enable-benchmarks   0,25s user 0,04s system 99% cpu 0,302 total
```

```
PkgId (PkgName "servant-auth-client") (Ver [0,4,0,0])
CompNameLib
  base-4.12.0.0
  bytestring-0.10.8.2
  containers-0.6.0.1
  servant-0.16.2
  servant-auth-0.3.2.0
  servant-client-core-0.16

PkgId (PkgName "servant-auth-client") (Ver [0,4,0,0])
CompNameTest "spec"
  QuickCheck-2.13.2
  aeson-1.4.6.0
  base-4.12.0.0
  bytestring-0.10.8.2
  hspec-2.7.1
  http-client-0.6.4
  http-types-0.12.3
  jose-0.8.2.0
  servant-0.16.2
  servant-auth-0.3.2.0
  servant-auth-client-0.4.0.0
  servant-auth-server-0.4.4.0
  servant-client-0.16.0.1
  servant-server-0.16.2
  time-1.8.0.2
  transformers-0.5.6.2
  wai-3.2.2.1
  warp-3.2.28

PkgId (PkgName "servant-auth-server") (Ver [0,4,4,0])
CompNameLib
  aeson-1.4.6.0
  base-4.12.0.0
  base64-bytestring-1.0.0.2
  blaze-builder-0.4.1.0
  bytestring-0.10.8.2
  case-insensitive-1.2.1.0
  cookie-0.4.5
  data-default-class-0.1.2.0
  entropy-0.4.1.5
  http-types-0.12.3
  jose-0.8.2.0
  lens-4.17.1
  memory-0.14.18
  monad-time-0.3.1.0
  mtl-2.2.2
  servant-0.16.2
  servant-auth-0.3.2.0
  servant-server-0.16.2
  tagged-0.8.6
  text-1.2.3.1
  time-1.8.0.2
  unordered-containers-0.2.10.0
  wai-3.2.2.1
```

**Comment by phadej** [comment]
```diff
% cabal-plan diff --plan-json master.plan.json --relative .

Package versions
~~~~~~~~~~~~~~~~

-base-compat-batteries-0.10.5 lib
+base-compat-batteries-0.11.0 lib
-generics-sop-0.4.0.1 lib
+generics-sop-0.5.0.0 lib
-hashable-1.2.7.0 lib
+hashable-1.3.0.0 lib
-http2-1.6.5 lib
+http2-2.0.3 lib
-lens-4.17.1
+lens-4.18.1
-lens-4.17.1 lib
+lens-4.18.1 lib
-lens-4.17.1 setup
+lens-4.18.1 setup
-lens-aeson-1.0.2
+lens-aeson-1.1
-lens-aeson-1.0.2 lib
+lens-aeson-1.1 lib
-lens-aeson-1.0.2 setup
+lens-aeson-1.1 setup
-memory-0.14.18 lib
+memory-0.15.0 lib
-network-3.0.1.1 lib
+network-3.1.1.0 lib
-sop-core-0.4.0.0 lib
+sop-core-0.5.0.0 lib
-swagger2-2.3.1.1
+swagger2-2.4
-swagger2-2.3.1.1 lib
+swagger2-2.4 lib
-swagger2-2.3.1.1 setup
+swagger2-2.4 setup
+type-equality-1 lib
-warp-3.2.28 lib
+warp-3.3.4 lib
```

**Comment by phadej** [comment]
With older warp tests run fast (the time includes rebuilding)

```
% time cabal run -w ghc-8.6.5 --enable-tests --enable-benchmarks servant-auth-client:spec --constraint 'warp ^>=3.2'
...
cabal run -w ghc-8.6.5 --enable-tests --enable-benchmarks  --constraint   217,77s user 18,15s system 115% cpu 3:25,05 total
```

is this fault of test-setup or `warp-3.3`? (`servant` tests run with `warp-3.3` and i don't remember they being noticeably slower, but we don't quickcheck there).

**Pull request merged**
