### PR TITLE
Followup on #54: Make XSRF optional

### PR DESCRIPTION
**Pull request by plredmond**
This changeset resolves @jkarni's [request](https://github.com/haskell-servant/servant-auth/pull/54#issuecomment-351450740) for @3noch to fix the tests in https://github.com/haskell-servant/servant-auth/pull/54 which resulted in that PR being [reverted](https://github.com/haskell-servant/servant-auth/pull/54#ref-commit-f637608) just after it was merged.

It also resolves the 4th todo-item from https://github.com/haskell-servant/servant-auth/issues/64, _Add option without cookies_. 

However, this changeset undoes part of #54, namely its name, _Add check-origin method for CSRF_. The addition of the versatile hook for rejecting requests seemed like a bigger fish than making XSRF optional, and so https://github.com/haskell-servant/servant-auth/issues/53 remains unfixed.
```diff
   data CookieSettings = CookieSettings {
   ...
-  -- | An arbitrary check for the request. Use this to implement validating
-  --   the Origin/Referer headers. Default @const True@.
-  , cookieCheckRequest      :: !(Request -> Bool)
-  } deriving (Generic)
```

### CODE REVIEW

**Comment by plredmond** [comment]
@3noch No problem! I needed this functionality for something I'm working on. Sorry for cutting out the `cookieCheckRequest` & associated calls.

**Comment by domenkozar** [comment]
```
$ git grep -i xsrf | wc -l
45
$ git grep -i csrf | wc -l
27
```

I didn't see that in the diff - I do agree consistency is important so nevermind my comment.

**Comment by domenkozar** [comment]
I've tested with `defaultCookieSettings { cookieXsrfSetting = Nothing }` and can confirm POST requests now have no XSRF checking and `NO-XSRF-TOKEN` cookie exists.

**Comment by domenkozar** [comment]
@plredmond could you rebase please?

**Comment by plredmond** [comment]
Sure

**Comment by domenkozar** [comment]
@plredmond could you also add a test case for `clearSession`?

**Comment by plredmond** [comment]
Yep. I'll do that Friday or Saturday.

**Comment by plredmond** [comment]
@domenkozar `clearSession` was working because it cleared the session cookie which prevents further authentication.

However, `clearSession` logic was unconditionally adding a cookie named `NO-XSRF-COOKIE`. That has been fixed and tested in 05dd6f5. The tests have an extra authenticated call to `GET /` which I could remove if you think it's not necessary.

Additionally 5f78fc4 changes all server-spec tests not to rely on the default name for the session cookie. Let me know if you want this reverted.

**Comment by plredmond** [comment]
Ok.. it looks like I can't use a few pieces of `wreq` or `http-client` because they aren't a part of the GHC-7.10.3 environment. I've got that environment building locally now and will see if I can get this working.

**Comment by plredmond** [comment]
Hey, I think this is ready for review again. I didn't mention it, but the
build for all versions is working now.

**Comment by domenkozar** [comment]
@plredmond do you think it would be better to delete the cookie instead of setting value to "value"? For example one might check for existence of the cookie if someone is signed in (not in a secure way).

**Comment by plredmond** [comment]
I think you're right that deleting the cookie would be semantically
cleaner. I don't know why the original author set the cookie to "value"
instead of deleting the cookie. One possible explanation is that cookie
deletion was flakey on older browsers. IE. A browser willing to set & read
cookies is likely willing to set a cookie to a dummy value (where deletion
might not work).

**Pull request merged**
