### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by dmjio**
Syntax highlighting

### CODE REVIEW

**Comment by jkarni** [comment]
Thanks - does `servant-auth-server/executables/Readme.lhs` also work with the changes? Unfortunately symlinks never work properly, so we have to keep those two in sync manually if we want to make sure they're being tested.

**Comment by domenkozar** [comment]
@jkarni what exactly doesn't work with symlinks - it seems to be ok for https://github.com/well-typed/pretty-sop

**Comment by jkarni** [comment]
If it works, perfect. I remember trying and failing (git broke hardlinks, and something else was wrong with symlinks) but I may just have missed something obvious.

**Comment by phadej** [comment]
https://www.quora.com/How-does-git-handle-symbolic-links-on-Windows

**Comment by domenkozar** [comment]
Took suggestions from @jkarni and opened https://github.com/haskell-servant/servant-auth/pull/100

@phadej me neither, I'd ignore windows until we have a windows contributor that wants to help us figure this one out (in worst case they can't run tests)

**Pull request closed without merging**
