### PR TITLE
Add utility functions for reading and writing a key to a file

### LINKED ISSUE #35: functions for reading and writing keys
first off, kudos! it was surprisingly easy to add auth to my app with this.

Now that i want to push it into prod, i need some way to not recreate the key every time i restart the process. is there an approved way to do that? should i consider Jose.Crypto as part of the public api?

### PR DESCRIPTION
**Pull request by mschristiansen**
The functions are simple, but it takes a bit of digging around in JOSE before figuring out how to write them. I've been using them in one application and need them in another. This fixes #35 .

### CODE REVIEW

**Comment by domenkozar** [comment]
It's hard to draw a line between the core api and helper functions, but it feels like these should be helpers functions for JOSE if anything.

**Comment by mschristiansen** [comment]
I agree that it isn't clear cut, but decided to add the functions for ease of use. Adding them in `jose` would be more difficult, since you would have to support all the different encryption schemes.

Everyone using `servant-auth` in production will have to write the key to a file (or similar) and currently you'll have to figure it out for yourself and you'll have to dig all the way down to `cryptonite`.

Adding these few lines add no new dependencies to `servant-auth-server`, but writing the code in your own project requires you to explicitly import `cryptonite, jose, and bytestring`.

**Comment by mschristiansen** [comment]
@domenkozar not convinced? I'm not sure how to move this to either "merge" or "close". Is there a down side to merging? Not much additional maintenance. Convenience to library user is real. Everyone will need to write the key to a file or similar.

**Comment by domenkozar** [comment]
My biggest concern is that someone will want to add different string variations and convenience becomes maintenance inconvenience. But I'll merge as to draw the line :)

**Comment by mschristiansen** [comment]
Thanks. I'll try to help with the maintenance :-)

**Comment by domenkozar** [comment]
Appreciated @mschristiansen :)

**Pull request merged**
